import random

genders = ["Male", "Female"]
items = ['Blouse',
 'Sweater',
 'Jeans',
 'Sandals',
 'Sneakers',
 'Shirt',
 'Shorts',
 'Coat',
 'Handbag',
 'Shoes',
 'Dress',
 'Skirt',
 'Sunglasses',
 'Pants',
 'Jacket',
 'Hoodie',
 'Jewelry',
 'T-shirt',
 'Scarf',
 'Hat',
 'Socks',
 'Backpack',
 'Belt',
 'Boots',
 'Gloves',
 'Swimsuit',
 'Watch',
 'Tie',
 'Vest',
 'Cardigan',
 'Raincoat',
 'Loafers',
 'Cufflinks',
 'Earrings',
 'Necklace',
 'Bracelet',
 'Cap',
 'Flip-flops',
 'Overalls',
 'Tracksuit',
 'Windbreaker']

categories = ['Clothing', 'Footwear', 'Outerwear', 'Accessories']
sizes = ['L', 'S', 'M', 'XL']
colors = ['Gray',
 'Maroon',
 'Turquoise',
 'White',
 'Charcoal',
 'Silver',
 'Pink',
 'Purple',
 'Olive',
 'Gold',
 'Violet',
 'Teal',
 'Lavender',
 'Black',
 'Green',
 'Peach',
 'Red',
 'Cyan',
 'Brown',
 'Beige',
 'Orange',
 'Indigo',
 'Yellow',
 'Magenta',
 'Blue']
locations = ['Kentucky',
 'Maine',
 'Massachusetts',
 'Rhode Island',
 'Oregon',
 'Wyoming',
 'Montana',
 'Louisiana',
 'West Virginia',
 'Missouri',
 'Arkansas',
 'Hawaii',
 'Delaware',
 'New Hampshire',
 'New York',
 'Alabama',
 'Mississippi',
 'North Carolina',
 'California',
 'Oklahoma',
 'Florida',
 'Texas',
 'Nevada',
 'Kansas',
 'Colorado',
 'North Dakota',
 'Illinois',
 'Indiana',
 'Arizona',
 'Alaska',
 'Tennessee',
 'Ohio',
 'New Jersey',
 'Maryland',
 'Vermont',
 'New Mexico',
 'South Carolina',
 'Idaho',
 'Pennsylvania',
 'Connecticut',
 'Utah',
 'Virginia',
 'Georgia',
 'Nebraska',
 'Iowa',
 'South Dakota',
 'Minnesota',
 'Washington',
 'Wisconsin',
 'Michigan']
frequency = ['Fortnightly',
 'Weekly',
 'Annually',
 'Quarterly',
 'Bi-Weekly',
 'Monthly',
 'Every 3 Months']
payment_methods = ['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer', 'Debit Card', 'Cryptocurrency']
shipping_type = ['Express',
 'Free Shipping',
 'Next Day Air',
 'Standard',
 '2-Day Shipping',
 'Store Pickup',
 'Same Day Delivery',
 'Overnight Shipping',
 'International Shipping']
seasons = ['Spring', 'Summer', 'Fall', 'Winter']

def generate_random_data(num_records):
    data = []
    for i in range(1, num_records + 1):
        record = {
            'Customer ID': i,
            'Age': random.randint(18, 70),
            'Gender': random.choice(genders),
            'Item Purchased': random.choice(items),
            'Category': random.choice(categories),
            'Purchase Amount (USD)': random.randint(20, 99),
            'Location': random.choice(locations),
            'Size': random.choice(sizes),
            'Color': random.choice(colors),
            'Season': random.choice(seasons),
            'Review Rating': round(random.uniform(1, 5), 1),
            'Subscription Status': random.choice(["Yes", "No"]),
            'Shipping Type': random.choice(shipping_type),
            'Discount Applied': random.choice(["Yes", "No"]),
            'Promo Code Used': random.choice(["Yes", "No"]),
            'Previous Purchases': random.randint(0, 99),
            'Payment Method': random.choice(payment_methods),
            'Frequency of Purchases': random.choice(frequency)
        }
        data.append(record)
    return data

if __name__ == "__main__":
    import pandas as pd

    num_records = 20000
    data = generate_random_data(num_records)
    df = pd.DataFrame(data)
    df.to_csv("big_input.csv", index=False)
